#!/usr/bin/bash
if [[ $1 = '' ]]
then
	echo "you must specify at least a word!!!"
	exit 0
fi
result=$(cat vocab.txt | grep $1)
echo $result

word=$(echo $result | awk '{print $8}' | cut -d ":" -f 1)
if [[ $word = '' ]]
then
	trans en:id $1
	echo -e "\n\n$1 not found in your vocab!!!"
	echo -n "Do you want to add $1 to new vocab list? (y/n): "
	read answer

	if [[ $answer = 'y' ]]
	then
		./add_vocab $1
	else
		exit 0
	fi
else
	trans en:id $1
fi

